### ISSUE TITLE
Not working on the new macbook 16 inch m1 pro

### ISSUE THREAD

**Issue by ivands** [chrisguttandin/dynamo-db-local#108]
The following code used to work on my older intel MacBook.
```javascript
const AWS = require('aws-sdk');
const dynamoDbLocal = require('dynamo-db-local');

async function init() {
	var process = await dynamoDbLocal.spawn({
		port: 8888
	});

	const service = new AWS.DynamoDB({
		apiVersion: 		'2016-11-23',
		endpoint: 		"http://localhost:8888",
		region: 		'eu-west-1',
		sslEnabled:		false,
		accessKeyId:		'fake',
		secretAccessKey:	'fake',
	});

	const client = new AWS.DynamoDB.DocumentClient({
		service
	});

	result = await service.listTables().promise()
	console.log(result);
}

init();
```

But now I get the following error:
```
UnknownEndpoint: Inaccessible host: `localhost'. This service may not be available in the `eu-west-1' region.
```

So I'm wondering what the issue is here.

**Comment by chrisguttandin** [comment]
Hi @ivands, thanks for reporting this.

Unfortunately I can't reproduce this myself. Can you please check if something is actually running on `localhost:8888`? 

Maybe it works if you use the explicit IP `127.0.0.1:8888`. But that's just a wild guess.

**Comment by ivands** [comment]
I'm sure nothing is running on that port.
I've done a little research and it seems dynamodb-local can't run on java for ARM.
If I try to run dynamodb-local manually I get the following error:

```WARNING: [sqlite] cannot open DB[7]: com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: /opt/homebrew/Caskroom/dynamodb-local/latest/DynamoDBLocal_lib/libsqlite4java-osx.dylib: dlopen(/opt/homebrew/Caskroom/dynamodb-local/latest/DynamoDBLocal_lib/libsqlite4java-osx.dylib, 0x0001): tried: '/opt/homebrew/Caskroom/dynamodb-local/latest/DynamoDBLocal_lib/libsqlite4java-osx.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/libsqlite4java-osx.dylib' (no such file)```

I'm guessing Java for x86_64 is needed running through rosetta.

**Comment by chrisguttandin** [comment]
Thanks for investigating this further. I'm not sure if there is anything that could be done here to fix this. Probably adding a note to the readme is all that can be done.

Do you have a better idea?

**Comment by ivands** [comment]
Ok, so the fix is to install Java for x86_64 and running Java through rosetta 2.
You can force command-line apps in Rosetta 2 / x86 mode by prefixing with it with ```arch -x86_64```.

So I installed Java like this:
```arch -x86_64 brew install temurin```

After that everything works fine.
Maybe you can add a little note about this in de readme.

**Comment by chrisguttandin** [comment]
Thanks for figuring this out and for writing it down. Do you want to submit a PR for adding it to the readme? I think you should be credited as the author of these changes.

**Comment by chrisguttandin** [comment]
Hi @ivands, I finally added an option to run DynamoDB Local with Docker. This should make it work on M1 Macs even without Rosetta.

```js
dynamoDbLocal.spawn({ command: 'docker' });
```
