### ISSUE TITLE
Network DNS error

### ISSUE THREAD

**Issue by mgentil-premaccess** [chrisguttandin/dynamo-db-local#110]
HI,

I'm using the package for my unit testing.

But when I start my tests  it raises a DNS error :
```
Error: getaddrinfo ENOTFOUND dynamodb.test.amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
```

My teardown.ts
```js
import { ChildProcess } from 'child_process';
import build from './index';

declare global {
    var dynamoProcess: ChildProcess | undefined;
}

export default async function() {
    const table = build().getTable();

    if (await table.exists()) {
        await table.deleteTable('DeleteTableForever');
    }

    if (global.dynamoProcess) {
        global.dynamoProcess.kill();
    }
};

```

My setup.ts: 
```js
import { ChildProcess } from 'child_process';
import build from './index';
// @ts-ignore
import local from 'dynamo-db-local';

export default async function () {
    global.dynamoProcess = local.spawn() as ChildProcess;
    await new Promise((resolve) => setTimeout(resolve, 1000));

    const table = build().getTable();

    if (!(await table.exists())) {
        await table.createTable();
    }
}

```

I don't understand why it trying to reach that dns 😅

**Comment by chrisguttandin** [comment]
Hi @mgentil-premaccess,

it looks like DynamoDB is not configured to use `localhost:8000` as the endpoint. I guess `"test"` is the value that you specify as the region and by default the DynamoDB client uses the region to construct the URL of the endpoint like that: `dynamodb.${region}.amazonaws.com`.

**Comment by mgentil-premaccess** [comment]
Hi @chrisguttandin,

Effectively the region was configured with "test". Passed to AWS known region (like  region: 'eu-west-1') fix the problem.

Thanks a lot for your quick help!
