### ISSUE TITLE
How to stop started Docker container

### ISSUE THREAD

**Issue by mxro** [chrisguttandin/dynamo-db-local#114]
Thank you for this library!

When starting a new instance of the local DynamoDB instance using the `command: 'docker'`, it launches without any problems:

```typescript
    console.debug('Starting local DynamoDB with Docker');
    const pr = dynamoDBLocal.spawn({
      port: MAPPED_PORT,
      command: 'docker',
      path: null,
    });
    return {
      port: MAPPED_PORT,
      stop: async () => {
        pr.kill();
      },
    };
```

However, it seems that when calling `kill` on the spawned process, the Docker container continues to run.

Maybe adding the `--init` argument to the command for running Docker could resolve this issue?

**Comment by chrisguttandin** [comment]
Hi @mxro,

I'm not sure what exactly the `--init` flag does. But maybe the problem is caused by your `stop()` function. It looks a bit suspicious to me since it's an `async` function but it doesn't contain any `await` and doesn't return anything.

I oftentimes use something like this to wait for the process to be killed.

```js
const stop = (process) => new Promise((resolve) => {
    process.stdout.once('end', () => resolve());
    process.kill();
});
```

Hopefully that helps.

**Comment by mxro** [comment]
Thank you for getting back to me!

I have tried with:

```typescript
    const pr = dynamoDBLocal.spawn({
      port: MAPPED_PORT,
      command: 'docker',
      path: null,
    });
    const stop = () =>
      new Promise<void>((resolve) => {
        pr.stdout.once('end', () => resolve());
        pr.kill();
      });
```

And it is the same result. I think the root of the problem is that when the spawned process is stopped, Docker doesn't stop the container. But it may do so when the `--init` flag is used.

**Comment by chrisguttandin** [comment]
I just checked again locally. I works for me.™ ;-)

I haven't payed any attention to the way I start the container so far since this issue is about stopping it again. However I now noticed that I'm using the `stdio` option, too. There was a change in Node.js recently (#112) which required this adjustment.

I'm currently doing this:

```js
const process = spawn({ command: 'docker', stdio: ['inherit', 'pipe', 'pipe'] });
```

**Comment by mxro** [comment]
Thank you for checking it again!

I created a sample project to recreate the issue: https://github.com/mxro/dynamodb-local-stop

Here the [test script](https://github.com/mxro/dynamodb-local-stop/blob/master/index.test.js) that recreates the issue for me:

```javascript

const dynamoDbLocal = require('dynamo-db-local');
const { execSync } = require("child_process");

jest.setTimeout(60000);

function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

it('Should start and stop DynamoDB Local', async () => {

  console.log('Containers before start');
  console.log(execSync('docker container ls').toString());
  
  const dynamoDbLocalProcess = dynamoDbLocal.spawn({command: 'docker', path: null});
  console.log('DynamoDB Local process started. Waiting for Docker container to spin up ...');

  await sleep(10000);

  dynamoDbLocalProcess.kill();
  console.log('DynamoDB Local process stopped');

  console.log('Containers after stop');
  console.log(execSync('docker container ls').toString());
});
```

This is the output the script produces when running it on my machine:

```

  console.log
    Containers before start

      at Object.log (index.test.js:23:11)

  console.log
    CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

      at Object.log (index.test.js:24:11)

  console.log
    DynamoDB Local process started. Waiting for Docker container to spin up ...

      at Object.log (index.test.js:27:11)

  console.log
    DynamoDB Local process stopped

      at Object.log (index.test.js:32:11)

  console.log
    Containers after stop

      at Object.log (index.test.js:34:11)

  console.log
    CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS         PORTS
       NAMES
    70d760529ddf   amazon/dynamodb-local:1.21.0   "java -jar DynamoDBL…"   10 seconds ago   Up 9 seconds   0.0.0.0:8000->8000/tcp   suspicious_goldstine

      at Object.log (index.test.js:35:11)
```

Note the container still runs after the process is killed.

When removing the ` await sleep(10000);`, the issue cannot be reproduced. I assume this is due to the process starting the Docker container not running long enough before the container is started. However, with adding the sleep, this is always reproducible to me.

**Comment by chrisguttandin** [comment]
Thanks a lot for providing the test case. I can confirm that I can reproduce the error, too. However applying the fix mentioned above (https://github.com/chrisguttandin/dynamo-db-local/issues/114#issuecomment-1478681762) works for me here as well.

I replaced ...

```js
dynamoDbLocalProcess.kill();
```

... with ...

```js
await new Promise((resolve) => {
  dynamoDbLocalProcess.stdout.once('end', () => resolve());
  dynamoDbLocalProcess.kill();
});
```

Does that also work on your end?

**Comment by mxro** [comment]
Thanks for checking and for the pointer.

I've updated the test case using the statement provided: https://github.com/mxro/dynamodb-local-stop/blob/master/index.test.js#L26

Unfortunately, the test result is still the same for me:

```
$ npm test

> dynamodb-local-stop@1.0.0 test
> jest

  console.log
    Containers before start

      at Object.log (index.test.js:15:11)

  console.log
    CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

      at Object.log (index.test.js:16:11)

  console.log
    DynamoDB Local process started. Waiting for Docker container to spin up ...

      at Object.log (index.test.js:19:11)

  console.log
    DynamoDB Local process stopped

      at Object.log (index.test.js:28:11)

  console.log
    Containers after stop

      at Object.log (index.test.js:30:11)

  console.log
    CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS         PORTS                    NAMES    0b28605e28e9   amazon/dynamodb-local:1.21.0   "java -jar DynamoDBL…"   10 seconds ago   Up 9 seconds   0.0.0.0:8000->8000/tcp   confident_goldwasser

      at Object.log (index.test.js:31:11)
```

Note I am running this on Windows using the latest Docker version.

I created a GitHub action to run it on Ubuntu - and there it seems to work: https://github.com/mxro/dynamodb-local-stop/blob/master/.github/workflows/action.yml#L21

```
Run npm test

> dynamodb-local-stop@1.0.0 test
> jest

  console.log
    Containers before start

      at Object.log (index.test.js:15:11)

  console.log
    CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

      at Object.log (index.test.js:16:11)

  console.log
    DynamoDB Local process started. Waiting for Docker container to spin up ...

      at Object.log (index.test.js:19:11)

  console.log
    Containers after start

      at Object.log (index.test.js:23:11)

  console.log
    CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS          PORTS                                       NAMES
    fd63bf7f9413   amazon/dynamodb-local:1.21.0   "java -jar DynamoDBL…"   49 seconds ago   Up 49 seconds   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   unruffled_clarke

      at Object.log (index.test.js:24:11)

  console.log
    DynamoDB Local process stopped

      at Object.log (index.test.js:31:11)

  console.log
    Containers after stop

      at Object.log (index.test.js:33:11)

  console.log
    CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

      at Object.log (index.test.js:34:11)

PASS ./index.test.js (61.141 s)
  ✓ Should start and stop DynamoDB Local (60811 ms)
```

So could be a Windows specific problem? 

Unfortunately, I wasn't able to get the test case to run successfully on a job using `windows-latest`.

**Comment by chrisguttandin** [comment]
By coincidence I watched this video over the weekend. They mention that the DNS resolution in Node.js has changed and that it might have caused some trouble with Docker before.

https://www.youtube.com/watch?v=Yl5mVte-wdw&t=1790

Maybe an update of Node.js solves the problem. At least one can hope. :-)

**Comment by mxro** [comment]
Ah, very interesting! I've been using Node `v18.5.0`. They mention a command line option to revert back to a behaviour from an older version. Do you know which option they are referring to? I tried running with Node v16 as well but also no luck.

btw, any ideas why running `spawn` from DynamoDB local does not seem to result in any new containers being started when testing in a GitHub actions on `windows-latest`?

```
> dynamodb-local-stop@1.0.0 test
> jest
  console.log
    Containers before start
      at Object.log (index.test.js:15:11)
  console.log
    CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
      at Object.log (index.test.js:16:11)
  console.log
    DynamoDB Local process started. Waiting for Docker container to spin up ...
      at Object.log (index.test.js:19:11)
  console.log
    Containers after start
      at Object.log (index.test.js:23:11)
  console.log
    CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
      at Object.log (index.test.js:24:11)
FAIL ./index.test.js (241.058 s)
  × Should start and stop DynamoDB Local (240011 ms)
  ● Should start and stop DynamoDB Local
    thrown: "Exceeded timeout of 240000 ms for a test.
```

It also seems to time out on this:

```
await new Promise((resolve) => {
    dynamoDbLocalProcess.stdout.once('end', () => resolve());
    dynamoDbLocalProcess.kill();
  });

```

Here the GitHub workflow definition: https://github.com/mxro/dynamodb-local-stop/blob/master/.github/workflows/action.yml#L10

Running using `ubuntu-latest` seems to work without problems.

**Comment by chrisguttandin** [comment]
I think it's the [`--dns-result-order=order`](https://nodejs.org/dist/latest-v18.x/docs/api/cli.html#--dns-result-orderorder) flag. Maybe it works when setting it to `'ipv4first'`. I'm keeping my fingers crossed that this makes a difference.

**Comment by mxro** [comment]
Thanks for the info! Tried running as per above, but unfortunately still no luck!

btw, I still haven't had any luck trying to run `dynamo-db-local` using `windows-latest` runner on GitHub actions. Essentially it just doesn't start any Docker container. If you the tests for this project could also run using `windows-latest` runner, I would be happy to adapt that then for the test project I've set up!

**Comment by chrisguttandin** [comment]
Hi @mxro, does the new [detached](https://github.com/chrisguttandin/dynamo-db-local#detached) option introduced by @o-alexandrov in #116 make any difference for you?

**Comment by mxro** [comment]
@chrisguttandin  Thanks for following up.

Did some tests today and left a comment on the PR.

Overall, situation is still the same:

- The container remains running after the local dynamodb is 'stopped'
- Tests fail when using `windows-latest`

This is both with and without utilising the new `detached` option.

**Comment by chrisguttandin** [comment]
Hi @mxro,

for some reason I can suddenly reproduce the problem on macOS. I suspect it was triggered by a Docker update. In an attempt to come up with a solution which is not a breaking change, I added another parameter to specify the name of the Docker container. That name can then be used with `docker stop`.

```js
import { exec } from 'child_process';
import { spawn } from 'dynamo-db-local';

spawn({ command: 'docker', name: 'a-unique-name' });
// ....
exec('docker stop a-unique-name');
```

It's a bit ugly but it seems to work.

**Comment by mxro** [comment]
Thank you for this!

Confirmed this approach works and have updated my template accordingly!
