### ISSUE TITLE
v9 doesn't work

### ISSUE THREAD

**Issue by dgadelha** [chrisguttandin/dynamo-db-local#118]
Hi there and thanks for this lib! The recent v9 doesn't seem to be working:

```
Error: Unable to access jarfile ../lib/dynamodb_local_2024-04-16/DynamoDBLocal.jar
```

As far as I could see from the source code, it is referencing the [jarfile from `../lib/`](https://github.com/chrisguttandin/dynamo-db-local/blob/e069656bd4563ae3a4b8580b16c28b5dd555eb4b/src/factories/spawn.ts#L26), but the [build code is creating `build/node` and `build/es2019`](https://github.com/chrisguttandin/dynamo-db-local/blob/e069656bd4563ae3a4b8580b16c28b5dd555eb4b/package.json#L88).

The `createSpawn` command is not considering now that there is a new subfolder inside `build/`, resulting in java trying to access `build/lib/dynamodb_local_2024-04-16` instead of `lib/dynamodb_local_2024-04-16`

As a workaround, I'm using v8 here

**Comment by chrisguttandin** [comment]
Thanks a lot for reporting this. Version 9.1.1 should contain the fix.
